Repository DeveloperAcademy-POSTECH/MC2-Team8-Ssok, pull requests merged in 2023-07, with the labels that each got.

#113 #100/padding sunday
  Ssok.xcodeproj/project.pbxproj
  Ssok/Global/Extension/Font+.swift
  Ssok/Global/Extension/String.swift
  Ssok/Global/Extension/UIScreen+.swift
  Ssok/Global/Extension/View+.swift
  Ssok/Model/How.swift
  Ssok/Model/ScreenSize.swift
  Ssok/Model/Where.swift
  Ssok/ViewModel/AddMemberViewModel.swift
  Ssok/Views/AddMemberView.swift
  Ssok/Views/BallView.swift
  Ssok/Views/IntroView.swift
  Ssok/Views/MissionEndingView.swift
  Ssok/Views/MissionSmileView.swift
  Ssok/Views/Recycle/MissionCompleteView.swift
  Ssok/Views/Recycle/MissionTitleView.swift
  Ssok/Views/Recycle/MissionTopView.swift
  Ssok/Views/Recycle/MissionTypeView.swift
  Ssok/Views/StrawView.swift
Labels: refactoring

#114 refactor: refactor Decibel code
  Ssok.xcodeproj/project.pbxproj
  Ssok/Global/Extension/Font+.swift
  Ssok/Model/What.swift
  Ssok/ViewModel/MissionDecibelViewModel.swift
  Ssok/Views/BallView.swift
  Ssok/Views/MissionDecibelView.swift
  Ssok/Views/MissionEndingView.swift
  Ssok/Views/MissionSpeechView.swift
Labels: refactoring

#116 #100/refactoring pin
  Ssok.xcodeproj/project.pbxproj
  Ssok/Assets.xcassets/Colors/LightGray.colorset/Contents 2.json
  Ssok/Assets.xcassets/Colors/LightGray.colorset/Contents.json
  Ssok/Global/Extension/Font+.swift
  Ssok/ViewModel/BottleViewModel.swift
  Ssok/ViewModel/MissionShakeViewModel.swift
  Ssok/ViewModel/StrawViewModel.swift
  Ssok/Views/IntroView.swift
  Ssok/Views/MissionEndingView.swift
  Ssok/Views/MissionPedometerView.swift
  Ssok/Views/MissionShakeView.swift
  Ssok/Views/Recycle/MissionCompleteView.swift
  Ssok/Views/StrawView.swift
Labels: refactoring

#117 #111/refactoring stt
  Ssok.xcodeproj/project.pbxproj
  Ssok.xcodeproj/xcshareddata/xcschemes/Ssok.xcscheme
  Ssok/Global/Extension/Font+.swift
  Ssok/Model/What.swift
  Ssok/ViewModel/SpeechViewModel.swift
  Ssok/Views/MissionEndingView.swift
  Ssok/Views/MissionSpeechView.swift
  Ssok/Views/Recycle/MissionTitleView.swift
  Ssok/Views/Recycle/MissionTopView.swift
Labels: refactoring

#120 refactor: draw random only StrawView appear
  Ssok.xcodeproj/project.pbxproj
  Ssok/SsokApp.swift
  Ssok/ViewModel/AddMemberViewModel.swift
  Ssok/ViewModel/RandomContents.swift
  Ssok/ViewModel/RandomMember.swift
  Ssok/Views/AddMemberView.swift
  Ssok/Views/MissionEndingView.swift
  Ssok/Views/Recycle/MissionCompleteView.swift
  Ssok/Views/StrawView.swift
Labels: refactoring

#123 #118/mission ending view
  Ssok.xcodeproj/project.pbxproj
  Ssok/Assets.xcassets/Ending/imgEndingTop.imageset/imgEndingTop@1x.png
  Ssok/Assets.xcassets/Ending/imgEndingTop.imageset/imgEndingTop@2x.png
  Ssok/Assets.xcassets/Ending/imgEndingTop.imageset/imgEndingTop@3x.png
  Ssok/Model/What.swift
  Ssok/Views/AddMemberView.swift
  Ssok/Views/MissionEndingView.swift
Labels: refactoring

#124 #122/modify pin
  Ssok.xcodeproj/project.pbxproj
  Ssok/ViewModel/StrawViewModel.swift
  Ssok/Views/StrawView.swift
Labels: refactoring

#126 #125/refactoring change asset
  Ssok/Assets.xcassets/IntroView/imgIntroAdvertising.imageset/Contents.json
  Ssok/Assets.xcassets/IntroView/imgIntroAdvertising.imageset/Group 121@1x.png
  Ssok/Assets.xcassets/IntroView/imgIntroAdvertising.imageset/Group 121@2x.png
  Ssok/Assets.xcassets/IntroView/imgIntroAdvertising.imageset/Group 121@3x.png
  Ssok/Assets.xcassets/IntroView/imgIntroAdvertising.imageset/imgIntroAdvertising@1x.png
  Ssok/Assets.xcassets/IntroView/imgIntroAdvertising.imageset/imgIntroAdvertising@2x.png
  Ssok/Assets.xcassets/IntroView/imgIntroAdvertising.imageset/imgIntroAdvertising@3x.png
  Ssok/Views/IntroView.swift
Labels: refactoring

#130 #129/feature add alert about AR
  Ssok.xcodeproj/project.pbxproj
  Ssok/Model/ARUnableDevices.swift
  Ssok/Views/MissionEndingView.swift
Labels: feature

#132 fix: change pearl and straw words
  Ssok/Views/StrawView.swift
Labels: refactoring

#138 #137/fix addmember view
  Ssok.xcodeproj/project.pbxproj
  Ssok/Global/Extension/String.swift
  Ssok/Global/Extension/UITextField.swift
  Ssok/ViewModel/AddMemberViewModel.swift
  Ssok/Views/AddMemberView.swift
Labels: fix

#142 기존에 제출한 버전과 일부 수정사항 Merge
  README.md
  Ssok.xcodeproj/project.pbxproj
  Ssok/Assets.xcassets/AppIcon.appiconset/1024.png
  Ssok/Assets.xcassets/AppIcon.appiconset/114.png
  Ssok/Assets.xcassets/AppIcon.appiconset/120.png
  Ssok/Assets.xcassets/AppIcon.appiconset/180.png
  Ssok/Assets.xcassets/AppIcon.appiconset/29.png
  Ssok/Assets.xcassets/AppIcon.appiconset/40.png
  Ssok/Assets.xcassets/AppIcon.appiconset/57.png
  Ssok/Assets.xcassets/AppIcon.appiconset/58.png
  Ssok/Assets.xcassets/AppIcon.appiconset/60.png
  Ssok/Assets.xcassets/AppIcon.appiconset/80.png
  Ssok/Assets.xcassets/AppIcon.appiconset/87.png
  Ssok/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  Ssok/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: bug, fix, refactoring
